// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: littlegames/match/v1/match.proto

// The single source of truth for everything sent over a match socket.
//
// Go and TypeScript are both generated from this file, so the two sides cannot
// drift apart. Editing generated output instead of this file is always wrong.

package matchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Identifies what a match data frame carries.
//
// Nakama gives every frame an integer op code alongside its payload, and the
// receiver needs it to know which message to decode.
type OpCode int32

const (
	OpCode_OP_CODE_UNSPECIFIED OpCode = 0
	// Client to server.
	OpCode_OP_CODE_PLAYER_INPUT OpCode = 1
	// Server to client.
	OpCode_OP_CODE_SNAPSHOT OpCode = 2
)

// Enum value maps for OpCode.
var (
	OpCode_name = map[int32]string{
		0: "OP_CODE_UNSPECIFIED",
		1: "OP_CODE_PLAYER_INPUT",
		2: "OP_CODE_SNAPSHOT",
	}
	OpCode_value = map[string]int32{
		"OP_CODE_UNSPECIFIED":  0,
		"OP_CODE_PLAYER_INPUT": 1,
		"OP_CODE_SNAPSHOT":     2,
	}
)

func (x OpCode) Enum() *OpCode {
	p := new(OpCode)
	*p = x
	return p
}

func (x OpCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpCode) Descriptor() protoreflect.EnumDescriptor {
	return file_littlegames_match_v1_match_proto_enumTypes[0].Descriptor()
}

func (OpCode) Type() protoreflect.EnumType {
	return &file_littlegames_match_v1_match_proto_enumTypes[0]
}

func (x OpCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpCode.Descriptor instead.
func (OpCode) EnumDescriptor() ([]byte, []int) {
	return file_littlegames_match_v1_match_proto_rawDescGZIP(), []int{0}
}

// What a client is pressing, sent from client to server.
//
// Intent only, never a position: the server owns the simulation, so a tampered
// client can lie about which keys it holds and nothing more.
type PlayerInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonically increasing, assigned by the client.
	//
	// The server echoes the highest value it has processed back in the snapshot,
	// which is what lets the client drop acknowledged inputs and replay the rest
	// on top of the authoritative state.
	Seq           uint32 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Up            bool   `protobuf:"varint,2,opt,name=up,proto3" json:"up,omitempty"`
	Down          bool   `protobuf:"varint,3,opt,name=down,proto3" json:"down,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_littlegames_match_v1_match_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_littlegames_match_v1_match_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_littlegames_match_v1_match_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerInput) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PlayerInput) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

func (x *PlayerInput) GetDown() bool {
	if x != nil {
		return x.Down
	}
	return false
}

// The authoritative state, broadcast from server to client once per tick.
type Snapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server tick this state was produced on, counted from the match start.
	Tick          uint32         `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Players       []*PlayerState `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_littlegames_match_v1_match_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_littlegames_match_v1_match_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_littlegames_match_v1_match_proto_rawDescGZIP(), []int{1}
}

func (x *Snapshot) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *Snapshot) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

// One player, as the server sees them.
type PlayerState struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	UserId   string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// Highest input sequence number the server has applied for this player.
	LastProcessedSeq uint32 `protobuf:"varint,3,opt,name=last_processed_seq,json=lastProcessedSeq,proto3" json:"last_processed_seq,omitempty"`
	// The input the server acted on for the current tick.
	Up            bool `protobuf:"varint,4,opt,name=up,proto3" json:"up,omitempty"`
	Down          bool `protobuf:"varint,5,opt,name=down,proto3" json:"down,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_littlegames_match_v1_match_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_littlegames_match_v1_match_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_littlegames_match_v1_match_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerState) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlayerState) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerState) GetLastProcessedSeq() uint32 {
	if x != nil {
		return x.LastProcessedSeq
	}
	return 0
}

func (x *PlayerState) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

func (x *PlayerState) GetDown() bool {
	if x != nil {
		return x.Down
	}
	return false
}

var File_littlegames_match_v1_match_proto protoreflect.FileDescriptor

const file_littlegames_match_v1_match_proto_rawDesc = "" +
	"\n" +
	" littlegames/match/v1/match.proto\x12\x14littlegames.match.v1\"C\n" +
	"\vPlayerInput\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\rR\x03seq\x12\x0e\n" +
	"\x02up\x18\x02 \x01(\bR\x02up\x12\x12\n" +
	"\x04down\x18\x03 \x01(\bR\x04down\"[\n" +
	"\bSnapshot\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\rR\x04tick\x12;\n" +
	"\aplayers\x18\x02 \x03(\v2!.littlegames.match.v1.PlayerStateR\aplayers\"\x94\x01\n" +
	"\vPlayerState\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12,\n" +
	"\x12last_processed_seq\x18\x03 \x01(\rR\x10lastProcessedSeq\x12\x0e\n" +
	"\x02up\x18\x04 \x01(\bR\x02up\x12\x12\n" +
	"\x04down\x18\x05 \x01(\bR\x04down*Q\n" +
	"\x06OpCode\x12\x17\n" +
	"\x13OP_CODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14OP_CODE_PLAYER_INPUT\x10\x01\x12\x14\n" +
	"\x10OP_CODE_SNAPSHOT\x10\x02B3Z1littlegames.local/nakama/protocol/matchv1;matchv1b\x06proto3"

var (
	file_littlegames_match_v1_match_proto_rawDescOnce sync.Once
	file_littlegames_match_v1_match_proto_rawDescData []byte
)

func file_littlegames_match_v1_match_proto_rawDescGZIP() []byte {
	file_littlegames_match_v1_match_proto_rawDescOnce.Do(func() {
		file_littlegames_match_v1_match_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_littlegames_match_v1_match_proto_rawDesc), len(file_littlegames_match_v1_match_proto_rawDesc)))
	})
	return file_littlegames_match_v1_match_proto_rawDescData
}

var file_littlegames_match_v1_match_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_littlegames_match_v1_match_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_littlegames_match_v1_match_proto_goTypes = []any{
	(OpCode)(0),         // 0: littlegames.match.v1.OpCode
	(*PlayerInput)(nil), // 1: littlegames.match.v1.PlayerInput
	(*Snapshot)(nil),    // 2: littlegames.match.v1.Snapshot
	(*PlayerState)(nil), // 3: littlegames.match.v1.PlayerState
}
var file_littlegames_match_v1_match_proto_depIdxs = []int32{
	3, // 0: littlegames.match.v1.Snapshot.players:type_name -> littlegames.match.v1.PlayerState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_littlegames_match_v1_match_proto_init() }
func file_littlegames_match_v1_match_proto_init() {
	if File_littlegames_match_v1_match_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_littlegames_match_v1_match_proto_rawDesc), len(file_littlegames_match_v1_match_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_littlegames_match_v1_match_proto_goTypes,
		DependencyIndexes: file_littlegames_match_v1_match_proto_depIdxs,
		EnumInfos:         file_littlegames_match_v1_match_proto_enumTypes,
		MessageInfos:      file_littlegames_match_v1_match_proto_msgTypes,
	}.Build()
	File_littlegames_match_v1_match_proto = out.File
	file_littlegames_match_v1_match_proto_goTypes = nil
	file_littlegames_match_v1_match_proto_depIdxs = nil
}
