import { describe, expect, it } from 'vitest';
import {
  ARENA_BOXES,
  COLLIDERS,
  OCCLUDERS,
  SEATS,
  SPAWNS,
  SPAWN_AIM,
  mirrorZ,
  opponentOf,
} from '../src/arena.ts';
import { bodyBounds, restingBody } from '../src/body.ts';
import { GAP_DEPTH, WALL_HEIGHT, ZONE_NEAR_Z } from '../src/constants.ts';
import { overlaps } from '../src/bounds.ts';

describe('the arena', () => {
  it('has no box turned inside out', () => {
    for (const box of ARENA_BOXES) {
      expect(box.maxX).toBeGreaterThan(box.minX);
      expect(box.maxY).toBeGreaterThan(box.minY);
      expect(box.maxZ).toBeGreaterThan(box.minZ);
    }
  });

  it('is two exact halves, not two hand-typed ones', () => {
    // The far zone is generated by reflection, so there is no arrangement in
    // which one player has cover the other does not.
    const half = ARENA_BOXES.length / 2;
    expect(half).toBe(Math.floor(half));

    for (const [index, near] of ARENA_BOXES.slice(0, half).entries()) {
      expect(ARENA_BOXES[half + index]).toEqual(mirrorZ(near));
    }
  });

  it('puts nothing in the ravine, so a bullet crosses it unobstructed', () => {
    for (const box of ARENA_BOXES) {
      const insideGap = box.maxZ > -ZONE_NEAR_Z && box.minZ < ZONE_NEAR_Z;
      expect(insideGap).toBe(false);
    }
  });

  it('walls the near edge of each zone from the ground to the ceiling', () => {
    // Whatever stops a body must span the full width and the full height, or
    // there is a way across the ravine and the layout stops being two duelling
    // boxes.
    for (const near of [ZONE_NEAR_Z, -ZONE_NEAR_Z - 0.4]) {
      const barrier = COLLIDERS.filter(
        (box) => box.minZ <= near + 0.001 && box.maxZ >= near + 0.399,
      );
      const spansWidth = barrier.some((box) => box.minX <= -10 && box.maxX >= 10);
      const lowest = Math.min(...barrier.map((box) => box.minY));
      const highest = Math.max(...barrier.map((box) => box.maxY));

      expect(spansWidth).toBe(true);
      expect(lowest).toBeLessThanOrEqual(0);
      expect(highest).toBeGreaterThanOrEqual(WALL_HEIGHT);
    }
  });

  it('keeps the invisible barrier invisible, and only a barrier to movement', () => {
    const clips = ARENA_BOXES.filter((box) => box.kind === 'clip');

    expect(clips.length).toBe(2);
    for (const clip of clips) {
      expect(clip.blocksMovement).toBe(true);
      expect(clip.blocksSight).toBe(false);
      expect(clip.visible).toBe(false);
    }
  });

  it('spawns both players in the open, facing each other', () => {
    for (const seat of SEATS) {
      const standing = bodyBounds(restingBody(SPAWNS[seat]));
      for (const collider of COLLIDERS) {
        expect(overlaps(standing, collider)).toBe(false);
      }
    }

    expect(SPAWNS.north.z).toBe(-SPAWNS.south.z);
    expect(SPAWN_AIM.north.z).toBe(-SPAWN_AIM.south.z);
    // Each looks across the gap at the other.
    expect(Math.sign(SPAWN_AIM.south.z)).toBe(Math.sign(SPAWNS.north.z));
  });

  it('separates the two spawns by the gap and both zones', () => {
    expect(SPAWNS.south.z - SPAWNS.north.z).toBeGreaterThan(GAP_DEPTH);
  });

  it('keeps the collider and occluder lists in source order', () => {
    // Collision resolution and the Go port both walk these in order. A filter
    // preserves it; a Set or a map would not, and Go randomises map iteration
    // by design.
    const collidingSource = ARENA_BOXES.filter((box) => box.blocksMovement);
    const occludingSource = ARENA_BOXES.filter((box) => box.blocksSight);

    expect(COLLIDERS).toEqual(collidingSource);
    expect(OCCLUDERS).toEqual(occludingSource);
    expect(OCCLUDERS.length).toBeLessThan(COLLIDERS.length);
  });

  it('knows which seat faces which', () => {
    expect(opponentOf('north')).toBe('south');
    expect(opponentOf('south')).toBe('north');
  });
});
