// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: littlegames/arena/v1/arena.proto

// Everything sent over an Arena match socket.
//
// Go and TypeScript are both generated from this file. Two things here are
// unlike the other games and are the whole reason this protocol is worth
// reading: intent travels as quantised integers rather than as floats, and
// state comes back as exact doubles.
//
// The direction is deliberate. A client predicts its own body by replaying the
// commands it sent, so it must replay the very numbers the server executed —
// integers on power-of-two scales dequantise to the identical double in both
// languages, where a float would arrive rounded differently and drift a hair
// every tick. State travels the other way and is never re-derived: a snapshot
// is where prediction restarts from, so it carries the body bit for bit.

package arenav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpCode int32

const (
	OpCode_OP_CODE_UNSPECIFIED OpCode = 0
	// Client to server.
	OpCode_OP_CODE_PLAYER_INPUT OpCode = 1
	OpCode_OP_CODE_READY        OpCode = 3
	// Server to client.
	OpCode_OP_CODE_SNAPSHOT OpCode = 2
)

// Enum value maps for OpCode.
var (
	OpCode_name = map[int32]string{
		0: "OP_CODE_UNSPECIFIED",
		1: "OP_CODE_PLAYER_INPUT",
		3: "OP_CODE_READY",
		2: "OP_CODE_SNAPSHOT",
	}
	OpCode_value = map[string]int32{
		"OP_CODE_UNSPECIFIED":  0,
		"OP_CODE_PLAYER_INPUT": 1,
		"OP_CODE_READY":        3,
		"OP_CODE_SNAPSHOT":     2,
	}
)

func (x OpCode) Enum() *OpCode {
	p := new(OpCode)
	*p = x
	return p
}

func (x OpCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpCode) Descriptor() protoreflect.EnumDescriptor {
	return file_littlegames_arena_v1_arena_proto_enumTypes[0].Descriptor()
}

func (OpCode) Type() protoreflect.EnumType {
	return &file_littlegames_arena_v1_arena_proto_enumTypes[0]
}

func (x OpCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpCode.Descriptor instead.
func (OpCode) EnumDescriptor() ([]byte, []int) {
	return file_littlegames_arena_v1_arena_proto_rawDescGZIP(), []int{0}
}

type Phase int32

const (
	Phase_PHASE_UNSPECIFIED Phase = 0
	Phase_PHASE_WAITING     Phase = 1
	Phase_PHASE_COUNTDOWN   Phase = 2
	Phase_PHASE_PLAYING     Phase = 3
	Phase_PHASE_FINISHED    Phase = 4
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PHASE_WAITING",
		2: "PHASE_COUNTDOWN",
		3: "PHASE_PLAYING",
		4: "PHASE_FINISHED",
	}
	Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED": 0,
		"PHASE_WAITING":     1,
		"PHASE_COUNTDOWN":   2,
		"PHASE_PLAYING":     3,
		"PHASE_FINISHED":    4,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_littlegames_arena_v1_arena_proto_enumTypes[1].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_littlegames_arena_v1_arena_proto_enumTypes[1]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_littlegames_arena_v1_arena_proto_rawDescGZIP(), []int{1}
}

// Which half of the arena a player holds.
type Seat int32

const (
	Seat_SEAT_UNSPECIFIED Seat = 0
	Seat_SEAT_NORTH       Seat = 1
	Seat_SEAT_SOUTH       Seat = 2
)

// Enum value maps for Seat.
var (
	Seat_name = map[int32]string{
		0: "SEAT_UNSPECIFIED",
		1: "SEAT_NORTH",
		2: "SEAT_SOUTH",
	}
	Seat_value = map[string]int32{
		"SEAT_UNSPECIFIED": 0,
		"SEAT_NORTH":       1,
		"SEAT_SOUTH":       2,
	}
)

func (x Seat) Enum() *Seat {
	p := new(Seat)
	*p = x
	return p
}

func (x Seat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Seat) Descriptor() protoreflect.EnumDescriptor {
	return file_littlegames_arena_v1_arena_proto_enumTypes[2].Descriptor()
}

func (Seat) Type() protoreflect.EnumType {
	return &file_littlegames_arena_v1_arena_proto_enumTypes[2]
}

func (x Seat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Seat.Descriptor instead.
func (Seat) EnumDescriptor() ([]byte, []int) {
	return file_littlegames_arena_v1_arena_proto_rawDescGZIP(), []int{2}
}

// One tick of intent, sent from client to server.
//
// No angle appears anywhere: the client resolves its own yaw and pitch into
// world-space directions and sends those, which is what keeps sine and cosine
// out of a simulation that has to agree with a second implementation to the
// last bit. It gives nothing away — a client that can look anywhere could
// already move in any direction, and the only thing direction bits ever bought
// was a speed cap, which the server applies to this vector directly.
type PlayerInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonically increasing, assigned by the client.
	//
	// Echoed back in the snapshot, which is what lets the client drop
	// acknowledged commands and replay the rest on top of authoritative state.
	Seq uint32 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Movement intent across and along the arena, on a scale of 1024. At most
	// unit length once dequantised; anything longer is shortened by the server.
	MoveX int32 `protobuf:"zigzag32,2,opt,name=move_x,json=moveX,proto3" json:"move_x,omitempty"`
	MoveZ int32 `protobuf:"zigzag32,3,opt,name=move_z,json=moveZ,proto3" json:"move_z,omitempty"`
	// Where the player is looking, as a world-space vector on a scale of 8192.
	// Normalised by the server, so its length carries no meaning.
	AimX   int32 `protobuf:"zigzag32,4,opt,name=aim_x,json=aimX,proto3" json:"aim_x,omitempty"`
	AimY   int32 `protobuf:"zigzag32,5,opt,name=aim_y,json=aimY,proto3" json:"aim_y,omitempty"`
	AimZ   int32 `protobuf:"zigzag32,6,opt,name=aim_z,json=aimZ,proto3" json:"aim_z,omitempty"`
	Jump   bool  `protobuf:"varint,7,opt,name=jump,proto3" json:"jump,omitempty"`
	Crouch bool  `protobuf:"varint,8,opt,name=crouch,proto3" json:"crouch,omitempty"`
	// Aiming down the sights. Nothing in the rules reads it; it travels so the
	// opponent can be drawn doing it.
	Zoomed bool `protobuf:"varint,9,opt,name=zoomed,proto3" json:"zoomed,omitempty"`
	// Newest server tick this client had drawn when it sampled this command.
	//
	// How far the server rewinds the target to judge a shot. Clamped against the
	// ticks the server knows it broadcast, so it cannot buy time by claiming to
	// have seen the distant past; claiming to have seen less than it did is
	// allowed and only makes the shot resolve against fresher positions.
	SeenTick uint32 `protobuf:"varint,10,opt,name=seen_tick,json=seenTick,proto3" json:"seen_tick,omitempty"`
	// How many shots this client has fired in total, ever.
	//
	// A counter rather than a flag, for the same reason `seq` is one: a duplicate
	// delivery re-sends a number the server has already reached and fires
	// nothing, and a lost command is made good by the next one that arrives
	// rather than costing a shot. A flag would do neither.
	ShotsFired    uint32 `protobuf:"varint,11,opt,name=shots_fired,json=shotsFired,proto3" json:"shots_fired,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_littlegames_arena_v1_arena_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_littlegames_arena_v1_arena_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_littlegames_arena_v1_arena_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerInput) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PlayerInput) GetMoveX() int32 {
	if x != nil {
		return x.MoveX
	}
	return 0
}

func (x *PlayerInput) GetMoveZ() int32 {
	if x != nil {
		return x.MoveZ
	}
	return 0
}

func (x *PlayerInput) GetAimX() int32 {
	if x != nil {
		return x.AimX
	}
	return 0
}

func (x *PlayerInput) GetAimY() int32 {
	if x != nil {
		return x.AimY
	}
	return 0
}

func (x *PlayerInput) GetAimZ() int32 {
	if x != nil {
		return x.AimZ
	}
	return 0
}

func (x *PlayerInput) GetJump() bool {
	if x != nil {
		return x.Jump
	}
	return false
}

func (x *PlayerInput) GetCrouch() bool {
	if x != nil {
		return x.Crouch
	}
	return false
}

func (x *PlayerInput) GetZoomed() bool {
	if x != nil {
		return x.Zoomed
	}
	return false
}

func (x *PlayerInput) GetSeenTick() uint32 {
	if x != nil {
		return x.SeenTick
	}
	return 0
}

func (x *PlayerInput) GetShotsFired() uint32 {
	if x != nil {
		return x.ShotsFired
	}
	return 0
}

// Client to server: whether this player is ready to start.
//
// The countdown waits for both. A player who is still tuning their controls is
// not kept waiting by an opponent who arrived first, and neither of them is
// dropped into a round they were not looking at.
type Ready struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_littlegames_arena_v1_arena_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_littlegames_arena_v1_arena_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_littlegames_arena_v1_arena_proto_rawDescGZIP(), []int{1}
}

func (x *Ready) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

// A body, as the server holds it. Exact doubles, in metres.
//
// Every field the simulation needs to advance from here is present, because
// this is where a client's prediction restarts: replaying unacknowledged
// commands from a body missing its vertical speed would put the player back on
// the ground mid-jump.
type Body struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Feet, not eyes.
	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float64 `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	// Vertical speed. There is no horizontal inertia to carry.
	Vy        float64 `protobuf:"fixed64,4,opt,name=vy,proto3" json:"vy,omitempty"`
	Grounded  bool    `protobuf:"varint,5,opt,name=grounded,proto3" json:"grounded,omitempty"`
	Crouching bool    `protobuf:"varint,6,opt,name=crouching,proto3" json:"crouching,omitempty"`
	// Where this body is in its stride, from zero to one.
	//
	// Simulated rather than animated: the limbs that are drawn are the limbs that
	// will be shot at, so both ends have to agree on where they are.
	GaitPhase float64 `protobuf:"fixed64,7,opt,name=gait_phase,json=gaitPhase,proto3" json:"gait_phase,omitempty"`
	// How far into a crouch, from standing to fully down. A number rather than a
	// flag because a body spends most of a crouch between the two.
	CrouchAmount float64 `protobuf:"fixed64,8,opt,name=crouch_amount,json=crouchAmount,proto3" json:"crouch_amount,omitempty"`
	// How big a step this body is taking, from standing still to a full run.
	//
	// The phase cannot say it on its own: a walk has its feet together only
	// halfway through a step, and the other foot is then at the top of its swing,
	// so no phase describes a figure standing still.
	GaitPower     float64 `protobuf:"fixed64,9,opt,name=gait_power,json=gaitPower,proto3" json:"gait_power,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Body) Reset() {
	*x = Body{}
	mi := &file_littlegames_arena_v1_arena_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Body) ProtoMessage() {}

func (x *Body) ProtoReflect() protoreflect.Message {
	mi := &file_littlegames_arena_v1_arena_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Body.ProtoReflect.Descriptor instead.
func (*Body) Descriptor() ([]byte, []int) {
	return file_littlegames_arena_v1_arena_proto_rawDescGZIP(), []int{2}
}

func (x *Body) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Body) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Body) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Body) GetVy() float64 {
	if x != nil {
		return x.Vy
	}
	return 0
}

func (x *Body) GetGrounded() bool {
	if x != nil {
		return x.Grounded
	}
	return false
}

func (x *Body) GetCrouching() bool {
	if x != nil {
		return x.Crouching
	}
	return false
}

func (x *Body) GetGaitPhase() float64 {
	if x != nil {
		return x.GaitPhase
	}
	return 0
}

func (x *Body) GetCrouchAmount() float64 {
	if x != nil {
		return x.CrouchAmount
	}
	return 0
}

func (x *Body) GetGaitPower() float64 {
	if x != nil {
		return x.GaitPower
	}
	return 0
}

// A unit vector.
type Vector3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	mi := &file_littlegames_arena_v1_arena_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_littlegames_arena_v1_arena_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_littlegames_arena_v1_arena_proto_rawDescGZIP(), []int{3}
}

func (x *Vector3) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

// One player, as the server sees them.
type PlayerState struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	UserId   string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Seat     Seat                   `protobuf:"varint,3,opt,name=seat,proto3,enum=littlegames.arena.v1.Seat" json:"seat,omitempty"`
	// Highest input sequence number the server has applied for this player.
	LastProcessedSeq uint32   `protobuf:"varint,4,opt,name=last_processed_seq,json=lastProcessedSeq,proto3" json:"last_processed_seq,omitempty"`
	Body             *Body    `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Aim              *Vector3 `protobuf:"bytes,6,opt,name=aim,proto3" json:"aim,omitempty"`
	Alive            bool     `protobuf:"varint,7,opt,name=alive,proto3" json:"alive,omitempty"`
	Score            uint32   `protobuf:"varint,8,opt,name=score,proto3" json:"score,omitempty"`
	// Ticks left before this player is put back at their spawn.
	RespawnTicks uint32 `protobuf:"varint,9,opt,name=respawn_ticks,json=respawnTicks,proto3" json:"respawn_ticks,omitempty"`
	// Ticks left before they may fire again.
	CooldownTicks uint32 `protobuf:"varint,10,opt,name=cooldown_ticks,json=cooldownTicks,proto3" json:"cooldown_ticks,omitempty"`
	// Bumped every time this player respawns.
	//
	// The server refuses to rewind a target across one, so nobody is killed a
	// beat after reappearing. The client throws away its unacknowledged commands
	// when its own changes, so it does not replay a dead player's movement onto a
	// fresh spawn and skate out of it.
	SpawnEpoch uint32 `protobuf:"varint,11,opt,name=spawn_epoch,json=spawnEpoch,proto3" json:"spawn_epoch,omitempty"`
	Zoomed     bool   `protobuf:"varint,12,opt,name=zoomed,proto3" json:"zoomed,omitempty"`
	// Whether this player has said they are ready to start. Only meaningful
	// before the countdown opens; it is never cleared once a match is under way.
	Ready         bool `protobuf:"varint,13,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_littlegames_arena_v1_arena_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_littlegames_arena_v1_arena_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_littlegames_arena_v1_arena_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerState) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlayerState) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerState) GetSeat() Seat {
	if x != nil {
		return x.Seat
	}
	return Seat_SEAT_UNSPECIFIED
}

func (x *PlayerState) GetLastProcessedSeq() uint32 {
	if x != nil {
		return x.LastProcessedSeq
	}
	return 0
}

func (x *PlayerState) GetBody() *Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PlayerState) GetAim() *Vector3 {
	if x != nil {
		return x.Aim
	}
	return nil
}

func (x *PlayerState) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *PlayerState) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PlayerState) GetRespawnTicks() uint32 {
	if x != nil {
		return x.RespawnTicks
	}
	return 0
}

func (x *PlayerState) GetCooldownTicks() uint32 {
	if x != nil {
		return x.CooldownTicks
	}
	return 0
}

func (x *PlayerState) GetSpawnEpoch() uint32 {
	if x != nil {
		return x.SpawnEpoch
	}
	return 0
}

func (x *PlayerState) GetZoomed() bool {
	if x != nil {
		return x.Zoomed
	}
	return false
}

func (x *PlayerState) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

// A shot the server resolved, for the client to draw.
type ShotEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique and increasing within a match, so a client can tell a shot it has
	// already drawn from one it has not.
	Id      uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Shooter Seat     `protobuf:"varint,2,opt,name=shooter,proto3,enum=littlegames.arena.v1.Seat" json:"shooter,omitempty"`
	Origin  *Vector3 `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	// Where it stopped: a body, a wall, or the end of its range.
	Endpoint      *Vector3 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	HitPlayer     bool     `protobuf:"varint,5,opt,name=hit_player,json=hitPlayer,proto3" json:"hit_player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShotEvent) Reset() {
	*x = ShotEvent{}
	mi := &file_littlegames_arena_v1_arena_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShotEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShotEvent) ProtoMessage() {}

func (x *ShotEvent) ProtoReflect() protoreflect.Message {
	mi := &file_littlegames_arena_v1_arena_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShotEvent.ProtoReflect.Descriptor instead.
func (*ShotEvent) Descriptor() ([]byte, []int) {
	return file_littlegames_arena_v1_arena_proto_rawDescGZIP(), []int{5}
}

func (x *ShotEvent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShotEvent) GetShooter() Seat {
	if x != nil {
		return x.Shooter
	}
	return Seat_SEAT_UNSPECIFIED
}

func (x *ShotEvent) GetOrigin() *Vector3 {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *ShotEvent) GetEndpoint() *Vector3 {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *ShotEvent) GetHitPlayer() bool {
	if x != nil {
		return x.HitPlayer
	}
	return false
}

// The authoritative state, broadcast once per tick.
type Snapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server tick this state was produced on.
	Tick  uint32 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Phase Phase  `protobuf:"varint,2,opt,name=phase,proto3,enum=littlegames.arena.v1.Phase" json:"phase,omitempty"`
	// Ticks left in the countdown, zero outside it.
	PhaseTicks uint32         `protobuf:"varint,3,opt,name=phase_ticks,json=phaseTicks,proto3" json:"phase_ticks,omitempty"`
	Players    []*PlayerState `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
	// Set once the match is over.
	Winner Seat `protobuf:"varint,5,opt,name=winner,proto3,enum=littlegames.arena.v1.Seat" json:"winner,omitempty"`
	// The last few shots fired, not only this tick's.
	//
	// Snapshots travel unreliably, and a tracer that appeared in one frame alone
	// would sometimes never be seen at all. A window of them means a client that
	// dropped a snapshot still draws the shot, and the ids tell it which ones it
	// has already drawn.
	Shots         []*ShotEvent `protobuf:"bytes,6,rep,name=shots,proto3" json:"shots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_littlegames_arena_v1_arena_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_littlegames_arena_v1_arena_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_littlegames_arena_v1_arena_proto_rawDescGZIP(), []int{6}
}

func (x *Snapshot) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *Snapshot) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *Snapshot) GetPhaseTicks() uint32 {
	if x != nil {
		return x.PhaseTicks
	}
	return 0
}

func (x *Snapshot) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *Snapshot) GetWinner() Seat {
	if x != nil {
		return x.Winner
	}
	return Seat_SEAT_UNSPECIFIED
}

func (x *Snapshot) GetShots() []*ShotEvent {
	if x != nil {
		return x.Shots
	}
	return nil
}

var File_littlegames_arena_v1_arena_proto protoreflect.FileDescriptor

const file_littlegames_arena_v1_arena_proto_rawDesc = "" +
	"\n" +
	" littlegames/arena/v1/arena.proto\x12\x14littlegames.arena.v1\"\x8e\x02\n" +
	"\vPlayerInput\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\rR\x03seq\x12\x15\n" +
	"\x06move_x\x18\x02 \x01(\x11R\x05moveX\x12\x15\n" +
	"\x06move_z\x18\x03 \x01(\x11R\x05moveZ\x12\x13\n" +
	"\x05aim_x\x18\x04 \x01(\x11R\x04aimX\x12\x13\n" +
	"\x05aim_y\x18\x05 \x01(\x11R\x04aimY\x12\x13\n" +
	"\x05aim_z\x18\x06 \x01(\x11R\x04aimZ\x12\x12\n" +
	"\x04jump\x18\a \x01(\bR\x04jump\x12\x16\n" +
	"\x06crouch\x18\b \x01(\bR\x06crouch\x12\x16\n" +
	"\x06zoomed\x18\t \x01(\bR\x06zoomed\x12\x1b\n" +
	"\tseen_tick\x18\n" +
	" \x01(\rR\bseenTick\x12\x1f\n" +
	"\vshots_fired\x18\v \x01(\rR\n" +
	"shotsFired\"\x1d\n" +
	"\x05Ready\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\"\xdd\x01\n" +
	"\x04Body\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01z\x12\x0e\n" +
	"\x02vy\x18\x04 \x01(\x01R\x02vy\x12\x1a\n" +
	"\bgrounded\x18\x05 \x01(\bR\bgrounded\x12\x1c\n" +
	"\tcrouching\x18\x06 \x01(\bR\tcrouching\x12\x1d\n" +
	"\n" +
	"gait_phase\x18\a \x01(\x01R\tgaitPhase\x12#\n" +
	"\rcrouch_amount\x18\b \x01(\x01R\fcrouchAmount\x12\x1d\n" +
	"\n" +
	"gait_power\x18\t \x01(\x01R\tgaitPower\"3\n" +
	"\aVector3\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01z\"\xc8\x03\n" +
	"\vPlayerState\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12.\n" +
	"\x04seat\x18\x03 \x01(\x0e2\x1a.littlegames.arena.v1.SeatR\x04seat\x12,\n" +
	"\x12last_processed_seq\x18\x04 \x01(\rR\x10lastProcessedSeq\x12.\n" +
	"\x04body\x18\x05 \x01(\v2\x1a.littlegames.arena.v1.BodyR\x04body\x12/\n" +
	"\x03aim\x18\x06 \x01(\v2\x1d.littlegames.arena.v1.Vector3R\x03aim\x12\x14\n" +
	"\x05alive\x18\a \x01(\bR\x05alive\x12\x14\n" +
	"\x05score\x18\b \x01(\rR\x05score\x12#\n" +
	"\rrespawn_ticks\x18\t \x01(\rR\frespawnTicks\x12%\n" +
	"\x0ecooldown_ticks\x18\n" +
	" \x01(\rR\rcooldownTicks\x12\x1f\n" +
	"\vspawn_epoch\x18\v \x01(\rR\n" +
	"spawnEpoch\x12\x16\n" +
	"\x06zoomed\x18\f \x01(\bR\x06zoomed\x12\x14\n" +
	"\x05ready\x18\r \x01(\bR\x05ready\"\xe2\x01\n" +
	"\tShotEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x124\n" +
	"\ashooter\x18\x02 \x01(\x0e2\x1a.littlegames.arena.v1.SeatR\ashooter\x125\n" +
	"\x06origin\x18\x03 \x01(\v2\x1d.littlegames.arena.v1.Vector3R\x06origin\x129\n" +
	"\bendpoint\x18\x04 \x01(\v2\x1d.littlegames.arena.v1.Vector3R\bendpoint\x12\x1d\n" +
	"\n" +
	"hit_player\x18\x05 \x01(\bR\thitPlayer\"\x9a\x02\n" +
	"\bSnapshot\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\rR\x04tick\x121\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x1b.littlegames.arena.v1.PhaseR\x05phase\x12\x1f\n" +
	"\vphase_ticks\x18\x03 \x01(\rR\n" +
	"phaseTicks\x12;\n" +
	"\aplayers\x18\x04 \x03(\v2!.littlegames.arena.v1.PlayerStateR\aplayers\x122\n" +
	"\x06winner\x18\x05 \x01(\x0e2\x1a.littlegames.arena.v1.SeatR\x06winner\x125\n" +
	"\x05shots\x18\x06 \x03(\v2\x1f.littlegames.arena.v1.ShotEventR\x05shots*d\n" +
	"\x06OpCode\x12\x17\n" +
	"\x13OP_CODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14OP_CODE_PLAYER_INPUT\x10\x01\x12\x11\n" +
	"\rOP_CODE_READY\x10\x03\x12\x14\n" +
	"\x10OP_CODE_SNAPSHOT\x10\x02*m\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPHASE_WAITING\x10\x01\x12\x13\n" +
	"\x0fPHASE_COUNTDOWN\x10\x02\x12\x11\n" +
	"\rPHASE_PLAYING\x10\x03\x12\x12\n" +
	"\x0ePHASE_FINISHED\x10\x04*<\n" +
	"\x04Seat\x12\x14\n" +
	"\x10SEAT_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"SEAT_NORTH\x10\x01\x12\x0e\n" +
	"\n" +
	"SEAT_SOUTH\x10\x02B3Z1littlegames.local/nakama/protocol/arenav1;arenav1b\x06proto3"

var (
	file_littlegames_arena_v1_arena_proto_rawDescOnce sync.Once
	file_littlegames_arena_v1_arena_proto_rawDescData []byte
)

func file_littlegames_arena_v1_arena_proto_rawDescGZIP() []byte {
	file_littlegames_arena_v1_arena_proto_rawDescOnce.Do(func() {
		file_littlegames_arena_v1_arena_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_littlegames_arena_v1_arena_proto_rawDesc), len(file_littlegames_arena_v1_arena_proto_rawDesc)))
	})
	return file_littlegames_arena_v1_arena_proto_rawDescData
}

var file_littlegames_arena_v1_arena_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_littlegames_arena_v1_arena_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_littlegames_arena_v1_arena_proto_goTypes = []any{
	(OpCode)(0),         // 0: littlegames.arena.v1.OpCode
	(Phase)(0),          // 1: littlegames.arena.v1.Phase
	(Seat)(0),           // 2: littlegames.arena.v1.Seat
	(*PlayerInput)(nil), // 3: littlegames.arena.v1.PlayerInput
	(*Ready)(nil),       // 4: littlegames.arena.v1.Ready
	(*Body)(nil),        // 5: littlegames.arena.v1.Body
	(*Vector3)(nil),     // 6: littlegames.arena.v1.Vector3
	(*PlayerState)(nil), // 7: littlegames.arena.v1.PlayerState
	(*ShotEvent)(nil),   // 8: littlegames.arena.v1.ShotEvent
	(*Snapshot)(nil),    // 9: littlegames.arena.v1.Snapshot
}
var file_littlegames_arena_v1_arena_proto_depIdxs = []int32{
	2,  // 0: littlegames.arena.v1.PlayerState.seat:type_name -> littlegames.arena.v1.Seat
	5,  // 1: littlegames.arena.v1.PlayerState.body:type_name -> littlegames.arena.v1.Body
	6,  // 2: littlegames.arena.v1.PlayerState.aim:type_name -> littlegames.arena.v1.Vector3
	2,  // 3: littlegames.arena.v1.ShotEvent.shooter:type_name -> littlegames.arena.v1.Seat
	6,  // 4: littlegames.arena.v1.ShotEvent.origin:type_name -> littlegames.arena.v1.Vector3
	6,  // 5: littlegames.arena.v1.ShotEvent.endpoint:type_name -> littlegames.arena.v1.Vector3
	1,  // 6: littlegames.arena.v1.Snapshot.phase:type_name -> littlegames.arena.v1.Phase
	7,  // 7: littlegames.arena.v1.Snapshot.players:type_name -> littlegames.arena.v1.PlayerState
	2,  // 8: littlegames.arena.v1.Snapshot.winner:type_name -> littlegames.arena.v1.Seat
	8,  // 9: littlegames.arena.v1.Snapshot.shots:type_name -> littlegames.arena.v1.ShotEvent
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_littlegames_arena_v1_arena_proto_init() }
func file_littlegames_arena_v1_arena_proto_init() {
	if File_littlegames_arena_v1_arena_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_littlegames_arena_v1_arena_proto_rawDesc), len(file_littlegames_arena_v1_arena_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_littlegames_arena_v1_arena_proto_goTypes,
		DependencyIndexes: file_littlegames_arena_v1_arena_proto_depIdxs,
		EnumInfos:         file_littlegames_arena_v1_arena_proto_enumTypes,
		MessageInfos:      file_littlegames_arena_v1_arena_proto_msgTypes,
	}.Build()
	File_littlegames_arena_v1_arena_proto = out.File
	file_littlegames_arena_v1_arena_proto_goTypes = nil
	file_littlegames_arena_v1_arena_proto_depIdxs = nil
}
