// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: littlegames/battleship/v1/battleship.proto

// Everything sent over a Battleship match socket.
//
// Go and TypeScript are both generated from this file. Note what is absent: a
// snapshot never carries the opponent's fleet, only the cells the recipient has
// already fired at. Sending the board and hiding it in the interface would put
// the answer in the browser, where anyone can read it.

package battleshipv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpCode int32

const (
	OpCode_OP_CODE_UNSPECIFIED OpCode = 0
	// Client to server.
	OpCode_OP_CODE_PLACE_FLEET OpCode = 1
	OpCode_OP_CODE_FIRE        OpCode = 2
	// Server to client.
	OpCode_OP_CODE_SNAPSHOT OpCode = 3
	OpCode_OP_CODE_REFUSED  OpCode = 4
)

// Enum value maps for OpCode.
var (
	OpCode_name = map[int32]string{
		0: "OP_CODE_UNSPECIFIED",
		1: "OP_CODE_PLACE_FLEET",
		2: "OP_CODE_FIRE",
		3: "OP_CODE_SNAPSHOT",
		4: "OP_CODE_REFUSED",
	}
	OpCode_value = map[string]int32{
		"OP_CODE_UNSPECIFIED": 0,
		"OP_CODE_PLACE_FLEET": 1,
		"OP_CODE_FIRE":        2,
		"OP_CODE_SNAPSHOT":    3,
		"OP_CODE_REFUSED":     4,
	}
)

func (x OpCode) Enum() *OpCode {
	p := new(OpCode)
	*p = x
	return p
}

func (x OpCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpCode) Descriptor() protoreflect.EnumDescriptor {
	return file_littlegames_battleship_v1_battleship_proto_enumTypes[0].Descriptor()
}

func (OpCode) Type() protoreflect.EnumType {
	return &file_littlegames_battleship_v1_battleship_proto_enumTypes[0]
}

func (x OpCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpCode.Descriptor instead.
func (OpCode) EnumDescriptor() ([]byte, []int) {
	return file_littlegames_battleship_v1_battleship_proto_rawDescGZIP(), []int{0}
}

type Phase int32

const (
	Phase_PHASE_UNSPECIFIED Phase = 0
	Phase_PHASE_WAITING     Phase = 1
	Phase_PHASE_PLACEMENT   Phase = 2
	Phase_PHASE_PLAYING     Phase = 3
	Phase_PHASE_FINISHED    Phase = 4
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PHASE_WAITING",
		2: "PHASE_PLACEMENT",
		3: "PHASE_PLAYING",
		4: "PHASE_FINISHED",
	}
	Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED": 0,
		"PHASE_WAITING":     1,
		"PHASE_PLACEMENT":   2,
		"PHASE_PLAYING":     3,
		"PHASE_FINISHED":    4,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_littlegames_battleship_v1_battleship_proto_enumTypes[1].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_littlegames_battleship_v1_battleship_proto_enumTypes[1]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_littlegames_battleship_v1_battleship_proto_rawDescGZIP(), []int{1}
}

type Orientation int32

const (
	Orientation_ORIENTATION_UNSPECIFIED Orientation = 0
	Orientation_ORIENTATION_HORIZONTAL  Orientation = 1
	Orientation_ORIENTATION_VERTICAL    Orientation = 2
)

// Enum value maps for Orientation.
var (
	Orientation_name = map[int32]string{
		0: "ORIENTATION_UNSPECIFIED",
		1: "ORIENTATION_HORIZONTAL",
		2: "ORIENTATION_VERTICAL",
	}
	Orientation_value = map[string]int32{
		"ORIENTATION_UNSPECIFIED": 0,
		"ORIENTATION_HORIZONTAL":  1,
		"ORIENTATION_VERTICAL":    2,
	}
)

func (x Orientation) Enum() *Orientation {
	p := new(Orientation)
	*p = x
	return p
}

func (x Orientation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Orientation) Descriptor() protoreflect.EnumDescriptor {
	return file_littlegames_battleship_v1_battleship_proto_enumTypes[2].Descriptor()
}

func (Orientation) Type() protoreflect.EnumType {
	return &file_littlegames_battleship_v1_battleship_proto_enumTypes[2]
}

func (x Orientation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Orientation.Descriptor instead.
func (Orientation) EnumDescriptor() ([]byte, []int) {
	return file_littlegames_battleship_v1_battleship_proto_rawDescGZIP(), []int{2}
}

type ShotResult int32

const (
	ShotResult_SHOT_RESULT_UNSPECIFIED ShotResult = 0
	ShotResult_SHOT_RESULT_MISS        ShotResult = 1
	ShotResult_SHOT_RESULT_HIT         ShotResult = 2
	ShotResult_SHOT_RESULT_SUNK        ShotResult = 3
)

// Enum value maps for ShotResult.
var (
	ShotResult_name = map[int32]string{
		0: "SHOT_RESULT_UNSPECIFIED",
		1: "SHOT_RESULT_MISS",
		2: "SHOT_RESULT_HIT",
		3: "SHOT_RESULT_SUNK",
	}
	ShotResult_value = map[string]int32{
		"SHOT_RESULT_UNSPECIFIED": 0,
		"SHOT_RESULT_MISS":        1,
		"SHOT_RESULT_HIT":         2,
		"SHOT_RESULT_SUNK":        3,
	}
)

func (x ShotResult) Enum() *ShotResult {
	p := new(ShotResult)
	*p = x
	return p
}

func (x ShotResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShotResult) Descriptor() protoreflect.EnumDescriptor {
	return file_littlegames_battleship_v1_battleship_proto_enumTypes[3].Descriptor()
}

func (ShotResult) Type() protoreflect.EnumType {
	return &file_littlegames_battleship_v1_battleship_proto_enumTypes[3]
}

func (x ShotResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShotResult.Descriptor instead.
func (ShotResult) EnumDescriptor() ([]byte, []int) {
	return file_littlegames_battleship_v1_battleship_proto_rawDescGZIP(), []int{3}
}

// Where one ship sits. Its length comes from its position in the fleet.
type Placement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           uint32                 `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Column        uint32                 `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	Orientation   Orientation            `protobuf:"varint,3,opt,name=orientation,proto3,enum=littlegames.battleship.v1.Orientation" json:"orientation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Placement) Reset() {
	*x = Placement{}
	mi := &file_littlegames_battleship_v1_battleship_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Placement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Placement) ProtoMessage() {}

func (x *Placement) ProtoReflect() protoreflect.Message {
	mi := &file_littlegames_battleship_v1_battleship_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Placement.ProtoReflect.Descriptor instead.
func (*Placement) Descriptor() ([]byte, []int) {
	return file_littlegames_battleship_v1_battleship_proto_rawDescGZIP(), []int{0}
}

func (x *Placement) GetRow() uint32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *Placement) GetColumn() uint32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *Placement) GetOrientation() Orientation {
	if x != nil {
		return x.Orientation
	}
	return Orientation_ORIENTATION_UNSPECIFIED
}

// A cell someone fired at, and what it found.
type Shot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           uint32                 `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Column        uint32                 `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	Result        ShotResult             `protobuf:"varint,3,opt,name=result,proto3,enum=littlegames.battleship.v1.ShotResult" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shot) Reset() {
	*x = Shot{}
	mi := &file_littlegames_battleship_v1_battleship_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shot) ProtoMessage() {}

func (x *Shot) ProtoReflect() protoreflect.Message {
	mi := &file_littlegames_battleship_v1_battleship_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shot.ProtoReflect.Descriptor instead.
func (*Shot) Descriptor() ([]byte, []int) {
	return file_littlegames_battleship_v1_battleship_proto_rawDescGZIP(), []int{1}
}

func (x *Shot) GetRow() uint32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *Shot) GetColumn() uint32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *Shot) GetResult() ShotResult {
	if x != nil {
		return x.Result
	}
	return ShotResult_SHOT_RESULT_UNSPECIFIED
}

// Client to server: the whole fleet at once.
//
// All five at once rather than one ship at a time, because whether an
// arrangement is legal is a property of the arrangement.
type PlaceFleet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ships         []*Placement           `protobuf:"bytes,1,rep,name=ships,proto3" json:"ships,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceFleet) Reset() {
	*x = PlaceFleet{}
	mi := &file_littlegames_battleship_v1_battleship_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceFleet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceFleet) ProtoMessage() {}

func (x *PlaceFleet) ProtoReflect() protoreflect.Message {
	mi := &file_littlegames_battleship_v1_battleship_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceFleet.ProtoReflect.Descriptor instead.
func (*PlaceFleet) Descriptor() ([]byte, []int) {
	return file_littlegames_battleship_v1_battleship_proto_rawDescGZIP(), []int{2}
}

func (x *PlaceFleet) GetShips() []*Placement {
	if x != nil {
		return x.Ships
	}
	return nil
}

// Client to server: fire at a cell.
type Fire struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           uint32                 `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Column        uint32                 `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fire) Reset() {
	*x = Fire{}
	mi := &file_littlegames_battleship_v1_battleship_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fire) ProtoMessage() {}

func (x *Fire) ProtoReflect() protoreflect.Message {
	mi := &file_littlegames_battleship_v1_battleship_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fire.ProtoReflect.Descriptor instead.
func (*Fire) Descriptor() ([]byte, []int) {
	return file_littlegames_battleship_v1_battleship_proto_rawDescGZIP(), []int{3}
}

func (x *Fire) GetRow() uint32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *Fire) GetColumn() uint32 {
	if x != nil {
		return x.Column
	}
	return 0
}

// Server to client: why something was refused, in words meant to be shown.
type Refused struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Refused) Reset() {
	*x = Refused{}
	mi := &file_littlegames_battleship_v1_battleship_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Refused) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refused) ProtoMessage() {}

func (x *Refused) ProtoReflect() protoreflect.Message {
	mi := &file_littlegames_battleship_v1_battleship_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refused.ProtoReflect.Descriptor instead.
func (*Refused) Descriptor() ([]byte, []int) {
	return file_littlegames_battleship_v1_battleship_proto_rawDescGZIP(), []int{4}
}

func (x *Refused) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Server to client, built for one recipient.
type Snapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Phase Phase                  `protobuf:"varint,1,opt,name=phase,proto3,enum=littlegames.battleship.v1.Phase" json:"phase,omitempty"`
	// True when it is the recipient's turn to fire.
	YourTurn bool `protobuf:"varint,2,opt,name=your_turn,json=yourTurn,proto3" json:"your_turn,omitempty"`
	// The recipient's own fleet, in full, and every shot taken at it.
	YourFleet   []*Placement `protobuf:"bytes,3,rep,name=your_fleet,json=yourFleet,proto3" json:"your_fleet,omitempty"`
	Incoming    []*Shot      `protobuf:"bytes,4,rep,name=incoming,proto3" json:"incoming,omitempty"`
	YouAreReady bool         `protobuf:"varint,5,opt,name=you_are_ready,json=youAreReady,proto3" json:"you_are_ready,omitempty"`
	// Only the cells the recipient has fired at. Never the opponent's ships.
	Outgoing        []*Shot `protobuf:"bytes,6,rep,name=outgoing,proto3" json:"outgoing,omitempty"`
	OpponentReady   bool    `protobuf:"varint,7,opt,name=opponent_ready,json=opponentReady,proto3" json:"opponent_ready,omitempty"`
	OpponentPresent bool    `protobuf:"varint,8,opt,name=opponent_present,json=opponentPresent,proto3" json:"opponent_present,omitempty"`
	// How many of each side's ships are on the bottom.
	YourShipsSunk     uint32 `protobuf:"varint,9,opt,name=your_ships_sunk,json=yourShipsSunk,proto3" json:"your_ships_sunk,omitempty"`
	OpponentShipsSunk uint32 `protobuf:"varint,10,opt,name=opponent_ships_sunk,json=opponentShipsSunk,proto3" json:"opponent_ships_sunk,omitempty"`
	// Set once the game is over.
	Finished      bool `protobuf:"varint,11,opt,name=finished,proto3" json:"finished,omitempty"`
	YouWon        bool `protobuf:"varint,12,opt,name=you_won,json=youWon,proto3" json:"you_won,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_littlegames_battleship_v1_battleship_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_littlegames_battleship_v1_battleship_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_littlegames_battleship_v1_battleship_proto_rawDescGZIP(), []int{5}
}

func (x *Snapshot) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *Snapshot) GetYourTurn() bool {
	if x != nil {
		return x.YourTurn
	}
	return false
}

func (x *Snapshot) GetYourFleet() []*Placement {
	if x != nil {
		return x.YourFleet
	}
	return nil
}

func (x *Snapshot) GetIncoming() []*Shot {
	if x != nil {
		return x.Incoming
	}
	return nil
}

func (x *Snapshot) GetYouAreReady() bool {
	if x != nil {
		return x.YouAreReady
	}
	return false
}

func (x *Snapshot) GetOutgoing() []*Shot {
	if x != nil {
		return x.Outgoing
	}
	return nil
}

func (x *Snapshot) GetOpponentReady() bool {
	if x != nil {
		return x.OpponentReady
	}
	return false
}

func (x *Snapshot) GetOpponentPresent() bool {
	if x != nil {
		return x.OpponentPresent
	}
	return false
}

func (x *Snapshot) GetYourShipsSunk() uint32 {
	if x != nil {
		return x.YourShipsSunk
	}
	return 0
}

func (x *Snapshot) GetOpponentShipsSunk() uint32 {
	if x != nil {
		return x.OpponentShipsSunk
	}
	return 0
}

func (x *Snapshot) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *Snapshot) GetYouWon() bool {
	if x != nil {
		return x.YouWon
	}
	return false
}

var File_littlegames_battleship_v1_battleship_proto protoreflect.FileDescriptor

const file_littlegames_battleship_v1_battleship_proto_rawDesc = "" +
	"\n" +
	"*littlegames/battleship/v1/battleship.proto\x12\x19littlegames.battleship.v1\"\x7f\n" +
	"\tPlacement\x12\x10\n" +
	"\x03row\x18\x01 \x01(\rR\x03row\x12\x16\n" +
	"\x06column\x18\x02 \x01(\rR\x06column\x12H\n" +
	"\vorientation\x18\x03 \x01(\x0e2&.littlegames.battleship.v1.OrientationR\vorientation\"o\n" +
	"\x04Shot\x12\x10\n" +
	"\x03row\x18\x01 \x01(\rR\x03row\x12\x16\n" +
	"\x06column\x18\x02 \x01(\rR\x06column\x12=\n" +
	"\x06result\x18\x03 \x01(\x0e2%.littlegames.battleship.v1.ShotResultR\x06result\"H\n" +
	"\n" +
	"PlaceFleet\x12:\n" +
	"\x05ships\x18\x01 \x03(\v2$.littlegames.battleship.v1.PlacementR\x05ships\"0\n" +
	"\x04Fire\x12\x10\n" +
	"\x03row\x18\x01 \x01(\rR\x03row\x12\x16\n" +
	"\x06column\x18\x02 \x01(\rR\x06column\"!\n" +
	"\aRefused\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xa1\x04\n" +
	"\bSnapshot\x126\n" +
	"\x05phase\x18\x01 \x01(\x0e2 .littlegames.battleship.v1.PhaseR\x05phase\x12\x1b\n" +
	"\tyour_turn\x18\x02 \x01(\bR\byourTurn\x12C\n" +
	"\n" +
	"your_fleet\x18\x03 \x03(\v2$.littlegames.battleship.v1.PlacementR\tyourFleet\x12;\n" +
	"\bincoming\x18\x04 \x03(\v2\x1f.littlegames.battleship.v1.ShotR\bincoming\x12\"\n" +
	"\ryou_are_ready\x18\x05 \x01(\bR\vyouAreReady\x12;\n" +
	"\boutgoing\x18\x06 \x03(\v2\x1f.littlegames.battleship.v1.ShotR\boutgoing\x12%\n" +
	"\x0eopponent_ready\x18\a \x01(\bR\ropponentReady\x12)\n" +
	"\x10opponent_present\x18\b \x01(\bR\x0fopponentPresent\x12&\n" +
	"\x0fyour_ships_sunk\x18\t \x01(\rR\ryourShipsSunk\x12.\n" +
	"\x13opponent_ships_sunk\x18\n" +
	" \x01(\rR\x11opponentShipsSunk\x12\x1a\n" +
	"\bfinished\x18\v \x01(\bR\bfinished\x12\x17\n" +
	"\ayou_won\x18\f \x01(\bR\x06youWon*w\n" +
	"\x06OpCode\x12\x17\n" +
	"\x13OP_CODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13OP_CODE_PLACE_FLEET\x10\x01\x12\x10\n" +
	"\fOP_CODE_FIRE\x10\x02\x12\x14\n" +
	"\x10OP_CODE_SNAPSHOT\x10\x03\x12\x13\n" +
	"\x0fOP_CODE_REFUSED\x10\x04*m\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPHASE_WAITING\x10\x01\x12\x13\n" +
	"\x0fPHASE_PLACEMENT\x10\x02\x12\x11\n" +
	"\rPHASE_PLAYING\x10\x03\x12\x12\n" +
	"\x0ePHASE_FINISHED\x10\x04*`\n" +
	"\vOrientation\x12\x1b\n" +
	"\x17ORIENTATION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ORIENTATION_HORIZONTAL\x10\x01\x12\x18\n" +
	"\x14ORIENTATION_VERTICAL\x10\x02*j\n" +
	"\n" +
	"ShotResult\x12\x1b\n" +
	"\x17SHOT_RESULT_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SHOT_RESULT_MISS\x10\x01\x12\x13\n" +
	"\x0fSHOT_RESULT_HIT\x10\x02\x12\x14\n" +
	"\x10SHOT_RESULT_SUNK\x10\x03B=Z;littlegames.local/nakama/protocol/battleshipv1;battleshipv1b\x06proto3"

var (
	file_littlegames_battleship_v1_battleship_proto_rawDescOnce sync.Once
	file_littlegames_battleship_v1_battleship_proto_rawDescData []byte
)

func file_littlegames_battleship_v1_battleship_proto_rawDescGZIP() []byte {
	file_littlegames_battleship_v1_battleship_proto_rawDescOnce.Do(func() {
		file_littlegames_battleship_v1_battleship_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_littlegames_battleship_v1_battleship_proto_rawDesc), len(file_littlegames_battleship_v1_battleship_proto_rawDesc)))
	})
	return file_littlegames_battleship_v1_battleship_proto_rawDescData
}

var file_littlegames_battleship_v1_battleship_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_littlegames_battleship_v1_battleship_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_littlegames_battleship_v1_battleship_proto_goTypes = []any{
	(OpCode)(0),        // 0: littlegames.battleship.v1.OpCode
	(Phase)(0),         // 1: littlegames.battleship.v1.Phase
	(Orientation)(0),   // 2: littlegames.battleship.v1.Orientation
	(ShotResult)(0),    // 3: littlegames.battleship.v1.ShotResult
	(*Placement)(nil),  // 4: littlegames.battleship.v1.Placement
	(*Shot)(nil),       // 5: littlegames.battleship.v1.Shot
	(*PlaceFleet)(nil), // 6: littlegames.battleship.v1.PlaceFleet
	(*Fire)(nil),       // 7: littlegames.battleship.v1.Fire
	(*Refused)(nil),    // 8: littlegames.battleship.v1.Refused
	(*Snapshot)(nil),   // 9: littlegames.battleship.v1.Snapshot
}
var file_littlegames_battleship_v1_battleship_proto_depIdxs = []int32{
	2, // 0: littlegames.battleship.v1.Placement.orientation:type_name -> littlegames.battleship.v1.Orientation
	3, // 1: littlegames.battleship.v1.Shot.result:type_name -> littlegames.battleship.v1.ShotResult
	4, // 2: littlegames.battleship.v1.PlaceFleet.ships:type_name -> littlegames.battleship.v1.Placement
	1, // 3: littlegames.battleship.v1.Snapshot.phase:type_name -> littlegames.battleship.v1.Phase
	4, // 4: littlegames.battleship.v1.Snapshot.your_fleet:type_name -> littlegames.battleship.v1.Placement
	5, // 5: littlegames.battleship.v1.Snapshot.incoming:type_name -> littlegames.battleship.v1.Shot
	5, // 6: littlegames.battleship.v1.Snapshot.outgoing:type_name -> littlegames.battleship.v1.Shot
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_littlegames_battleship_v1_battleship_proto_init() }
func file_littlegames_battleship_v1_battleship_proto_init() {
	if File_littlegames_battleship_v1_battleship_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_littlegames_battleship_v1_battleship_proto_rawDesc), len(file_littlegames_battleship_v1_battleship_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_littlegames_battleship_v1_battleship_proto_goTypes,
		DependencyIndexes: file_littlegames_battleship_v1_battleship_proto_depIdxs,
		EnumInfos:         file_littlegames_battleship_v1_battleship_proto_enumTypes,
		MessageInfos:      file_littlegames_battleship_v1_battleship_proto_msgTypes,
	}.Build()
	File_littlegames_battleship_v1_battleship_proto = out.File
	file_littlegames_battleship_v1_battleship_proto_goTypes = nil
	file_littlegames_battleship_v1_battleship_proto_depIdxs = nil
}
